[package]
name = "grpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
ethers = { version = "2.0.13", features = ["rustls", "ws"] }
futures-util = "0.3.30"
http = "1.0.0"
prost = "0.12.3"
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-tokio"] }
tokio = { version = "1.36.0", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["default", "sync"] }
tonic = "0.10.2"
tonic-health = "0.10.2"
tonic-web = "0.10.2"
tower-http = { version = "0.5.1", features = ["cors"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[build-dependencies]
tonic-build = "0.10.2"

[[bin]]
name = "grpc"
path = "src/main.rs"
