[package]
name = "grpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = { version = "2.0.13", features = ["rustls", "ws"] }
futures-util = "0.3.30"
prost = "0.12.3"
sqlx = "0.7.3"
tokio = { version = "1.36.0", features = ["full"] }
tokio-stream = "0.1.14"
tonic = "0.10.2"
tonic-health = "0.10.2"
tracing = "0.1.40"

[build-dependencies]
tonic-build = "0.10.2"

[[bin]]
name = "grpc"
path = "src/main.rs"
